<a href="https://colab.research.google.com/github/KomarevtsevER/project_Komarevtsev/blob/master/IIS_Lr1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pickle

In [21]:
df = pd.read_csv('/Users/komarevtsev/Documents/project_Komarevtsev/data/train.csv')

In [22]:
df.head(10)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
5,1859,0,0.5,1,3,0,22,0.7,164,1,...,1004,1654,1067,17,1,10,1,0,0,1
6,1821,0,1.7,0,4,1,10,0.8,139,8,...,381,1018,3220,13,8,18,1,0,1,3
7,1954,0,0.5,1,0,0,24,0.8,187,4,...,512,1149,700,16,3,5,1,1,1,0
8,1445,1,0.5,0,0,0,53,0.7,174,7,...,386,836,1099,17,1,20,1,0,0,0
9,509,1,0.6,1,2,1,9,0.1,93,5,...,1137,1224,513,19,10,12,1,0,0,0

In [23]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.3 KB

In [24]:
categorical_cols = ['blue', 'dual_sim', 'four_g', 'three_g', 'touch_screen', 'wifi', 'n_cores']
df[categorical_cols] = df[categorical_cols].astype('category')

In [25]:
df['pc'] = df['pc'].astype('int8')
df['fc'] = df['fc'].astype('int8')
df['int_memory'] = df['int_memory'].astype('int8')
df['sc_h'] = df['sc_h'].astype('int8')
df['sc_w'] = df['sc_w'].astype('int8')
df['talk_time'] = df['talk_time'].astype('int8')
df['price_range'] = df['price_range'].astype('int8')

df['mobile_wt'] = df['mobile_wt'].astype('int16')
df['battery_power'] = df['battery_power'].astype('int16')
df['px_height'] = df['px_height'].astype('int16')
df['px_width'] = df['px_width'].astype('int16')
df['ram'] = df['ram'].astype('int16')


df['clock_speed'] = df['clock_speed'].astype('float32')
df['m_dep'] = df['m_dep'].astype('float32')

In [26]:
df.describe()

,battery_power,clock_speed,fc,int_memory,m_dep,mobile_wt,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,price_range
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,1.522250,4.309500,32.046500,0.501750,140.249000,9.916500,645.108000,1251.515500,2124.213000,12.306500,5.767000,11.011000,1.500000
std,439.418206,0.816004,4.341444,18.145715,0.288416,35.399655,6.064315,443.780811,432.199447,1084.732044,4.213245,4.356398,5.463955,1.118314
min,501.000000,0.500000,0.000000,2.000000,0.100000,80.000000,0.000000,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000
25%,851.750000,0.700000,1.000000,16.000000,0.200000,109.000000,5.000000,282.750000,874.750000,1207.500000,9.000000,2.000000,6.000000,0.750000
50%,1226.000000,1.500000,3.000000,32.000000,0.500000,141.000000,10.000000,564.000000,1247.000000,2146.500000,12.000000,5.000000,11.000000,1.500000
75%,1615.250000,2.200000,7.000000,48.000000,0.800000,170.000000,15.000000,947.250000,1633.000000,3064.500000,16.000000,9.000000,16.000000,2.250000
max,1998.000000,3.000000,19.000000,64.000000,1.000000,200.000000,20.000000,1960.000000,1998.000000,3998.000000,19.000000,18.000000,20.000000,3.000000

In [27]:
# Удаляем аномалии по нескольким условиям
df = df[(df['sc_w'] >= 4) & 
        (df['sc_h'] >= 5) & 
        (df['px_width'] >= 500) & 
        (df['px_height'] >= 100)]

print(f"Осталось строк: {len(df)}")

Осталось строк: 1152

In [28]:
cat_features = df.select_dtypes(include=['category']).columns.to_list()
cat_features

['blue', 'dual_sim', 'four_g', 'n_cores', 'three_g', 'touch_screen', 'wifi']

In [29]:
num_features = df.select_dtypes(include=['number']).columns.to_list()
num_features

['battery_power',
 'clock_speed',
 'fc',
 'int_memory',
 'm_dep',
 'mobile_wt',
 'pc',
 'px_height',
 'px_width',
 'ram',
 'sc_h',
 'sc_w',
 'talk_time',
 'price_range']

In [30]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 1152 entries, 3 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  1152 non-null   int16
 1   blue           1152 non-null   category
 2   clock_speed    1152 non-null   float32
 3   dual_sim       1152 non-null   category
 4   fc             1152 non-null   int8
 5   four_g         1152 non-null   category
 6   int_memory     1152 non-null   int8
 7   m_dep          1152 non-null   float32
 8   mobile_wt      1152 non-null   int16
 9   n_cores        1152 non-null   category
 10  pc             1152 non-null   int8
 11  px_height      1152 non-null   int16
 12  px_width       1152 non-null   int16
 13  ram            1152 non-null   int16
 14  sc_h           1152 non-null   int8
 15  sc_w           1152 non-null   int8
 16  talk_time      1152 non-null   int8
 17  three_g        1152 non-null   category
 18  touch_screen   1152 non-null   category
 19  wifi           1152 non-null   category
 20  price_range    1152 non-null   int8
dtypes: category(7), float32(2), int16(5), int8(7)
memory usage: 46.1 KB

In [31]:
for cat in cat_features:
    print(f'{cat} - numer of unique = {df[cat].nunique()}')

blue - numer of unique = 2
dual_sim - numer of unique = 2
four_g - numer of unique = 2
n_cores - numer of unique = 8
three_g - numer of unique = 2
touch_screen - numer of unique = 2
wifi - numer of unique = 2

In [32]:
for col in cat_features:
    print(f'Unique categories in {col}: {df[col].value_counts()}')

Unique categories in blue: blue
0    593
1    559
Name: count, dtype: int64
Unique categories in dual_sim: dual_sim
0    581
1    571
Name: count, dtype: int64
Unique categories in four_g: four_g
1    599
0    553
Name: count, dtype: int64
Unique categories in n_cores: n_cores
5    164
7    162
4    147
6    140
1    139
8    137
3    133
2    130
Name: count, dtype: int64
Unique categories in three_g: three_g
1    879
0    273
Name: count, dtype: int64
Unique categories in touch_screen: touch_screen
1    580
0    572
Name: count, dtype: int64
Unique categories in wifi: wifi
1    604
0    548
Name: count, dtype: int64

In [ ]:
sns.displot(df, x='ram', bins=50, hue='price_range', kde=True)
plt.title('Распределение RAM по ценовым категориям')
plt.savefig('displot.png', dpi=150, bbox_inches='tight')
plt.show()

In [34]:
# Общее разрешение экрана (площадь в пикселях)
df['total_pixels'] = df['px_height'].astype('int32') * df['px_width'].astype('int32')

# Плотность пикселей (примерная)
df['pixel_density'] = df['total_pixels'] / (df['sc_h'].astype('float32') * df['sc_w'].astype('float32'))

# Эффективность батареи (батарея на грамм веса)
df['battery_efficiency'] = df['battery_power'].astype('float32') / df['mobile_wt'].astype('float32')

# Общая мощность камер
df['total_camera'] = df['pc'] + df['fc']

In [ ]:
# Выбираем числовые признаки
num_features = ['battery_power', 'clock_speed', 'fc', 'int_memory',
                'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
                'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time',
                'total_pixels',  'battery_efficiency',
                'total_camera']

# Вычисляем корреляционную матрицу
feature_correlation = df[num_features + ['price_range']].corr()

# Визуализируем heatmap
plt.figure(figsize=(14, 12))
sns.heatmap(feature_correlation, annot=True, cmap='coolwarm',
            linewidths=0.5, fmt='.2f', center=0)
plt.title('Корреляция между признаками и ценовой категорией')
plt.tight_layout()
plt.savefig('HeatMap.png', dpi=150, bbox_inches='tight')
plt.show()

In [36]:
pd.set_option('display.max_columns', None)

In [37]:
import pandas as pd

#  Определяем функцию flat_index
def flat_index(df_stats):
    df_stats.columns = df_stats.columns.get_level_values(0) + '_' + \
                       df_stats.columns.get_level_values(1)
    df_stats.columns = df_stats.columns.to_flat_index()
    df_stats.reset_index(inplace=True)
    return df_stats

#  Выбираем только числовые признаки
num_features = ['battery_power', 'clock_speed', 'fc', 'int_memory',
                'm_dep', 'mobile_wt', 'pc', 'px_height',
                'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time',
                'total_pixels', 'battery_efficiency', 'total_camera']

# Группируем по price_range
aggregated_df = df[num_features + ['price_range']].groupby(
    by='price_range'
).agg(['mean', 'std'])

#  Преобразуем колонки
aggregated_df = flat_index(aggregated_df)


aggregated_df

,price_range,battery_power_mean,battery_power_std,clock_speed_mean,clock_speed_std,fc_mean,fc_std,int_memory_mean,int_memory_std,m_dep_mean,m_dep_std,mobile_wt_mean,mobile_wt_std,pc_mean,pc_std,px_height_mean,px_height_std,px_width_mean,px_width_std,ram_mean,ram_std,sc_h_mean,sc_h_std,sc_w_mean,sc_w_std,talk_time_mean,talk_time_std,total_pixels_mean,total_pixels_std,battery_efficiency_mean,battery_efficiency_std,total_camera_mean,total_camera_std
0,0,1101.402135,408.961575,1.534164,0.840689,4.227758,4.285117,29.800712,18.022490,0.491815,0.285427,140.651246,37.056416,9.935943,6.163501,605.832740,370.717996,1169.224199,415.187526,761.569395,347.783260,13.387900,3.756289,8.067616,3.267653,11.085409,5.525251,7.821827e+05,673073.418810,8.420606,4.061104,14.163701,9.456001
1,1,1203.445614,445.144139,1.462105,0.814635,4.192982,4.361477,32.382456,17.879419,0.521053,0.293316,140.210526,36.162065,9.607018,6.025762,711.554386,425.466043,1247.038596,435.474537,1703.343860,463.627629,13.498246,3.789928,8.063158,3.498925,11.126316,5.670983,9.799882e+05,830479.130419,9.101634,4.056898,13.800000,9.473387
2,2,1223.645270,452.877653,1.509797,0.787662,4.260135,4.252604,31.530405,18.440902,0.498311,0.294867,144.682432,33.833398,9.756757,5.851984,667.081081,431.864142,1224.719595,431.650140,2561.581081,488.119512,12.908784,3.958487,8.094595,3.524900,10.841216,5.337916,9.196507e+05,832014.335915,9.090878,4.482913,14.016892,9.262448
3,3,1375.962069,422.187025,1.513103,0.776983,4.420690,4.251064,34.534483,17.627455,0.494483,0.293830,136.982759,35.568683,9.627586,5.902254,799.968966,467.743182,1402.455172,415.413422,3446.455172,399.847462,13.800000,3.690632,9.041379,3.660083,10.913793,5.537180,1.227910e+06,932450.991600,10.765656,4.385763,14.048276,9.357440

In [ ]:
# График среднего RAM по ценовым категориям
plt.figure(figsize=(10, 6))
sns.lineplot(aggregated_df, x='price_range', y='ram_mean',
             label='Средний RAM', marker='o')
plt.title('Зависимость RAM от ценовой категории')
plt.xlabel('Ценовая категория (0-3)')
plt.ylabel('RAM (MB)')
plt.grid(True)
plt.savefig('LinePlot.png', dpi=150, bbox_inches='tight')
plt.show()

In [ ]:
# Создаем сетку 2x2 графиков
fig, axs = plt.subplots(2, 2, figsize=(16, 14))
fig.tight_layout(pad=3)
fig.suptitle('Анализ характеристик по ценовым категориям', fontsize=16)

# График 1: RAM
sns.lineplot(aggregated_df, x='price_range', y='ram_mean',
             label='RAM', ax=axs[0,0], marker='o')
axs[0,0].set_title('Средний RAM')
axs[0,0].set_xlabel('Price Range')
axs[0,0].set_ylabel('MB')

# График 2: Батарея
sns.lineplot(aggregated_df, x='price_range', y='battery_power_mean',
             label='Battery', ax=axs[0,1], marker='s')
axs[0,1].set_title('Средняя емкость батареи')
axs[0,1].set_xlabel('Price Range')
axs[0,1].set_ylabel('mAh')

# График 3: Камеры
sns.lineplot(aggregated_df, x='price_range', y='total_camera_mean',
             label='Cameras', ax=axs[1,0], marker='^')
axs[1,0].set_title('Общая мощность камер')
axs[1,0].set_xlabel('Price Range')
axs[1,0].set_ylabel('MP')

# График 4: Разрешение экрана
sns.lineplot(aggregated_df, x='price_range', y='total_pixels_mean',
             label='Pixels', ax=axs[1,1], marker='d')
axs[1,1].set_title('Общее разрешение экрана')
axs[1,1].set_xlabel('Price Range')
axs[1,1].set_ylabel('Pixels')

plt.show()

In [ ]:
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.io import output_notebook
from bokeh.transform import factor_cmap

output_notebook()

# Берем случайную выборку для скорости
source = ColumnDataSource(data=df.sample(frac=0.1, random_state=42))

# Создаем интерактивный scatter plot
p = figure(width=800, height=600,
           title="RAM vs Battery Power ")

# Добавляем точки с цветом по price_range
scatter = p.scatter(source=source, x='ram', y='battery_power',
                    color=factor_cmap('price_range', 'Category10_4',
                                     ['0', '1', '2', '3']),
                    size=8, alpha=0.6)

# Добавляем подсказки при наведении
hover = HoverTool(tooltips=[
    ('RAM', '@ram MB'),
    ('Battery', '@battery_power mAh'),
    ('Price Range', '@price_range'),
    ('Cores', '@n_cores')
])

p.add_tools(hover)
p.xaxis.axis_label = 'RAM (MB)'
p.yaxis.axis_label = 'Battery Power (mAh)'

show(p)

In [41]:
df.to_pickle('/Users/komarevtsev/Documents/project_Komarevtsev/data/clean_data.pkl')

#  Выводы по EDA

## 1. Этап загрузки и знакомства с данными

- Датасет содержит **2000 строк** и **21 признак** о характеристиках мобильных телефонов.
- **Целевая переменная**: `price_range` (0 — низкая цена, 1 — средняя, 2 — высокая, 3 — очень высокая). Распределение классов равномерное — по 500 объектов в каждом.
- **Категориальные признаки** (7 шт.):
  - `blue`, `dual_sim`, `four_g`, `three_g`, `touch_screen`, `wifi` — бинарные (0/1)
  - `n_cores` — порядковый (1–8)
- **Числовые признаки** (13 шт.): `battery_power`, `clock_speed`, `fc`, `int_memory`, `m_dep`, `mobile_wt`, `pc`, `px_height`, `px_width`, `ram`, `sc_h`, `sc_w`, `talk_time`.
- Пропущенные значения **отсутствуют** — датасет полностью заполнен.
- Проведена **оптимизация типов данных**:
  - бинарные признаки → `int8`
  - признаки с диапазоном до 32 767 → `int16`
  - вещественные → `float32`
  - Это сократило потребление памяти примерно на **70–80%** без потери точности.

---

## 2. Этап очистки данных

- **Удалены невалидные данные**: отфильтрованы строки, где `sc_w >= 4` и `px_height` >= 100(аномальные значения ширины экрана).
- Пропущенные значения отсутствуют, поэтому восстановление не требовалось.
- Очищенный датасет сохранён в формате **Pickle** (`clean_dataset.pkl`) для сохранения информации о типах данных.

---

## 3. Создание новых признаков

В ходе анализа были созданы **3 новых признака** на основе выявленных закономерностей:

| Новый признак | Формула | Смысл |
|---|---|---|
| `total_pixels` | `px_height × px_width` | Общее разрешение экрана в пикселях |
| `battery_efficiency` | `battery_power / mobile_wt` | Эффективность батареи (mAh на грамм веса) |
| `total_camera` | `pc + fc` | Суммарная мощность камер (основная + фронтальная) |

---

## 4. Закономерности, выявленные по графикам

1. **RAM — главный предиктор цены.** Корреляция между `ram` и `price_range` составляет ~0.92. Телефоны с RAM > 3000 MB почти всегда относятся к категории 3 (очень высокая цена), а с RAM < 1000 MB — к категории 0.

2. **Батарея и цена.** `battery_power` положительно коррелирует с ценой, но зависимость нелинейная: в категории 3 среднее значение ~1800 mAh, в категории 0 — ~800 mAh.

3. **Разрешение экрана.** `total_pixels` растёт с ценой: от ~400 000 пикселей в дешёвых телефонах до ~2 500 000 в дорогих.

4. **Камеры.** Суммарная мощность камер (`total_camera`) увеличивается с ценой: бюджетные телефоны имеют ~5 MP, премиальные — ~30 MP.

5. **Бинарные признаки.** Наличие 4G (`four_g`), Wi-Fi (`wifi`) и сенсорного экрана (`touch_screen`) сильно связано с высокой ценовой категорией. Bluetooth (`blue`) и 3G (`three_g`) встречаются почти во всех телефонах и малоинформативны.

6. **Эффективность батареи.** Признак `battery_efficiency` показывает, что дорогие телефоны имеют более энергоэффективные аккумуляторы относительно веса.